[project]
name = "potehinson_sound_core"
version = "0.1.0"
description = ""
authors = [
    {name = "Uto4ka", email = "alezhestkov@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.2.3,<2.0.0",
    "potehinsonnet @ git+https://github.com/uto4e4ka/poteninson_net.git@dev",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.dependencies]
potehinsonnet = {develop = true}
